# -*- coding: utf-8 -*-
"""risk_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8xGWW6OH0JSMkA3O9b7eZyrezVlkzAB
"""

"""
Portfolio Risk Metrics Dashboard
Interactive VaR/ES backtesting with Basel-compliant validation
"""
import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from scipy.stats import norm, chi2
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# ============================================================================
# Core Risk Functions (refactored from your notebook)
# ============================================================================

def fetch_data(tickers, start_date, end_date):
    """Download adjusted close prices and compute returns"""
    data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=False, progress=False)
    adj_close = data['Adj Close'].dropna()
    returns = adj_close.pct_change().dropna()
    return adj_close, returns

def compute_portfolio_metrics(returns, weights=None):
    """Compute portfolio returns, volatility, and diversification benefit"""
    if weights is None:
        weights = np.ones(len(returns.columns)) / len(returns.columns)

    portfolio_returns = returns @ weights

    # Annualised metrics
    ann_return = portfolio_returns.mean() * 252
    ann_vol = portfolio_returns.std() * np.sqrt(252)

    # Individual volatilities
    ind_vols = returns.std() * np.sqrt(252)
    avg_ind_vol = ind_vols.mean()
    div_benefit = (avg_ind_vol - ann_vol) / avg_ind_vol

    return portfolio_returns, ann_return, ann_vol, div_benefit

def historical_var_es(returns, alpha_var=0.99, alpha_es=0.975, holding_days=10):
    """Historical VaR and Expected Shortfall"""
    var_1d = np.percentile(returns, (1 - alpha_var) * 100)
    es_threshold = np.percentile(returns, (1 - alpha_es) * 100)
    tail_returns = returns[returns <= es_threshold]
    es_1d = tail_returns.mean() if len(tail_returns) > 0 else var_1d

    var_10d = -var_1d * np.sqrt(holding_days)
    es_10d = -es_1d * np.sqrt(holding_days)

    return var_10d, es_10d

def parametric_var_es(returns, alpha_var=0.99, alpha_es=0.975, holding_days=10):
    """Delta-Normal VaR and Expected Shortfall"""
    mu = returns.mean()
    sigma = returns.std()

    z_var = norm.ppf(1 - alpha_var)
    z_es = norm.ppf(1 - alpha_es)

    var_10d = -(mu + sigma * z_var) * np.sqrt(holding_days)
    es_10d = -(mu + sigma * norm.pdf(z_es) / (1 - alpha_es)) * np.sqrt(holding_days)

    return var_10d, es_10d

def kupiec_test(returns, var_threshold, alpha=0.01):
    """Kupiec Proportion of Failures test"""
    n = len(returns)
    failures = int(np.sum(returns < -var_threshold))
    failure_rate = failures / n
    expected = n * alpha

    if failures == 0:
        LR = -2 * np.log((1 - alpha) ** n)
    elif failures == n:
        LR = -2 * np.log(alpha ** n)
    else:
        LR = -2 * np.log(
            ((1 - alpha) ** (n - failures) * alpha ** failures) /
            ((1 - failure_rate) ** (n - failures) * failure_rate ** failures)
        )

    p_value = 1 - chi2.cdf(LR, df=1)
    reject = p_value < 0.01

    return {
        'failures': failures,
        'expected': round(expected, 1),
        'failure_rate': f"{failure_rate:.2%}",
        'p_value': round(p_value, 4),
        'reject': reject,
        'passed': not reject
    }

def traffic_light(returns, var_threshold, alpha=0.01, window=250):
    """Basel Traffic Light test"""
    n = len(returns)
    failures = int(np.sum(returns < -var_threshold))
    scale = n / window
    green_max = int(4 * scale)
    yellow_max = int(9 * scale)

    if failures <= green_max:
        zone = "🟢 GREEN"
        status = "Accept"
    elif failures <= yellow_max:
        zone = "🟡 YELLOW"
        status = "Scrutinize"
    else:
        zone = "🔴 RED"
        status = "Reject"

    return {'failures': failures, 'zone': zone, 'status': status}

def rolling_var(returns, window=250, alpha=0.99, holding_days=10):
    """Rolling window VaR"""
    rolling_values = []
    for i in range(window, len(returns)):
        window_returns = returns.iloc[i - window:i]
        var = np.percentile(window_returns, (1 - alpha) * 100)
        rolling_values.append(-var * np.sqrt(holding_days))

    return pd.Series(rolling_values, index=returns.index[window:])

def compute_betas(returns, market_ticker='SPY'):
    """Compute CAPM betas against market"""
    if market_ticker not in returns.columns:
        return {}

    market_ret = returns[market_ticker]
    betas = {}
    for ticker in returns.columns:
        if ticker != market_ticker:
            cov_im = np.cov(returns[ticker], market_ret)[0, 1]
            beta = cov_im / np.var(market_ret)
            betas[ticker] = beta

    return betas

# ============================================================================
# Streamlit UI
# ============================================================================

st.set_page_config(
    page_title="Risk Metrics Dashboard",
    page_icon="📊",
    layout="wide"
)

st.title("📊 Portfolio Risk Metrics Dashboard")
st.markdown("Basel-compliant VaR/ES with backtesting validation")

# Sidebar configuration
with st.sidebar:
    st.header("⚙️ Configuration")

    # Ticker input
    default_tickers = "AAPL, MSFT, SPY, RELIANCE.NS, SAIL.NS"
    ticker_input = st.text_input("Tickers (comma-separated)", default_tickers)
    tickers = [t.strip() for t in ticker_input.split(",")]

    # Date range
    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("Start date", value=pd.to_datetime("2016-01-01"))
    with col2:
        end_date = st.date_input("End date", value=pd.to_datetime("2025-12-31"))

    # Risk parameters
    st.subheader("Risk Parameters")
    alpha_var = st.selectbox("VaR Confidence Level", [0.95, 0.99, 0.999], index=1)
    alpha_es = st.selectbox("ES Confidence Level", [0.95, 0.975, 0.99], index=1)
    holding_days = st.number_input("Holding Period (days)", min_value=1, max_value=20, value=10)

    # Advanced options
    with st.expander("Advanced Options"):
        rolling_window = st.number_input("Rolling Window (days)", min_value=50, max_value=500, value=250)
        train_split = st.date_input("Train/Test Split", value=pd.to_datetime("2022-01-01"))
        market_ticker = st.text_input("Market Benchmark", "SPY")

    # Run button
    run_btn = st.button("🚀 Run Analysis", type="primary", use_container_width=True)

# Main content
if run_btn:
    with st.spinner("Fetching data and computing metrics..."):
        try:
            # Fetch data
            prices, returns = fetch_data(tickers, start_date, end_date)

            if len(returns) == 0:
                st.error("No data retrieved. Check tickers and date range.")
                st.stop()

            # Portfolio construction (equal weight)
            portfolio_returns, port_ann_return, port_ann_vol, div_benefit = compute_portfolio_metrics(returns)

            # Train/test split
            split_date = pd.to_datetime(train_split)
            train_returns = portfolio_returns[portfolio_returns.index < split_date]
            test_returns = portfolio_returns[portfolio_returns.index >= split_date]

            # VaR thresholds from training data
            hist_var_1d = -np.percentile(train_returns, (1 - alpha_var) * 100)
            param_var_1d = -(train_returns.mean() + train_returns.std() * norm.ppf(1 - alpha_var))

            # Backtesting
            hist_backtest = kupiec_test(test_returns, hist_var_1d, alpha=1 - alpha_var)
            param_backtest = kupiec_test(test_returns, param_var_1d, alpha=1 - alpha_var)

            # Rolling VaR
            rolling_var_series = rolling_var(portfolio_returns, window=rolling_window, alpha=alpha_var, holding_days=holding_days)

            # Current VaR/ES
            hist_var, hist_es = historical_var_es(portfolio_returns, alpha_var, alpha_es, holding_days)
            param_var, param_es = parametric_var_es(portfolio_returns, alpha_var, alpha_es, holding_days)

            # Betas
            betas = compute_betas(returns, market_ticker)

            # Traffic Light
            tl_hist = traffic_light(test_returns, hist_var_1d, alpha=1 - alpha_var)

            # ===== DASHBOARD OUTPUT =====

            # Key metrics row
            st.subheader("📈 Key Risk Metrics")
            col1, col2, col3, col4, col5 = st.columns(5)
            col1.metric("Portfolio Volatility (Ann.)", f"{port_ann_vol:.2%}")
            col2.metric("Portfolio Return (Ann.)", f"{port_ann_return:.2%}")
            col3.metric("Diversification Benefit", f"{div_benefit:.1%}")
            col4.metric("10-day 99% VaR (Hist)", f"{hist_var:.2%}")
            col5.metric("10-day 97.5% ES (Hist)", f"{hist_es:.2%}")

            # VaR/ES comparison
            st.subheader("📊 VaR & Expected Shortfall Comparison")
            var_es_df = pd.DataFrame({
                'Metric': ['99% VaR (10-day)', '97.5% ES (10-day)'],
                'Historical': [f"{hist_var:.2%}", f"{hist_es:.2%}"],
                'Parametric': [f"{param_var:.2%}", f"{param_es:.2%}"]
            })
            st.dataframe(var_es_df, use_container_width=True, hide_index=True)

            # Backtesting results
            st.subheader("🔍 Backtesting Results (Out-of-Sample)")
            col1, col2 = st.columns(2)

            with col1:
                st.markdown("**Historical VaR**")
                st.metric("Failures", f"{hist_backtest['failures']} / {len(test_returns)}")
                st.metric("Expected", hist_backtest['expected'])
                st.metric("p-value", hist_backtest['p_value'])
                st.markdown(f"**Verdict:** {'✅ PASS' if hist_backtest['passed'] else '❌ FAIL'}")
                st.markdown(f"**Traffic Light:** {tl_hist['zone']}")

            with col2:
                st.markdown("**Parametric VaR**")
                st.metric("Failures", f"{param_backtest['failures']} / {len(test_returns)}")
                st.metric("Expected", param_backtest['expected'])
                st.metric("p-value", param_backtest['p_value'])
                st.markdown(f"**Verdict:** {'✅ PASS' if param_backtest['passed'] else '❌ FAIL'}")

            # Rolling VaR chart
            st.subheader("📉 Rolling 10-day 99% VaR")
            fig = go.Figure()
            fig.add_trace(go.Scatter(
                x=rolling_var_series.index,
                y=rolling_var_series,
                mode='lines',
                name=f'Rolling VaR ({rolling_window}-day window)',
                line=dict(color='red', width=1.5)
            ))
            fig.add_hline(y=hist_var, line_dash="dash", line_color="gray",
                         annotation_text=f"Fixed VaR: {hist_var:.2%}")
            fig.update_layout(
                title=f"Rolling {int(alpha_var*100)}% VaR",
                xaxis_title="Date",
                yaxis_title="Potential Loss",
                yaxis_tickformat=".0%",
                height=400
            )
            st.plotly_chart(fig, use_container_width=True)

            # Portfolio returns chart
            st.subheader("📈 Portfolio Returns with VaR Threshold")
            fig2 = go.Figure()
            fig2.add_trace(go.Scatter(
                x=portfolio_returns.index,
                y=portfolio_returns,
                mode='lines',
                name='Daily Returns',
                line=dict(color='blue', width=0.8),
                opacity=0.6
            ))
            fig2.add_hline(y=-hist_var_1d, line_dash="dash", line_color="red",
                          annotation_text=f"VaR Threshold ({hist_var_1d:.2%})")
            fig2.update_layout(
                title="Portfolio Returns",
                xaxis_title="Date",
                yaxis_title="Daily Return",
                yaxis_tickformat=".1%",
                height=400
            )
            st.plotly_chart(fig2, use_container_width=True)

            # Beta table
            if betas:
                st.subheader("📐 CAPM Betas")
                beta_df = pd.DataFrame([
                    {'Asset': k, 'Beta': f"{v:.3f}"} for k, v in betas.items()
                ])
                st.dataframe(beta_df, use_container_width=True, hide_index=True)

            # Summary statistics
            st.subheader("📊 Descriptive Statistics")
            stats_df = pd.DataFrame({
                'Ticker': returns.columns,
                'Ann. Return': returns.mean() * 252,
                'Ann. Vol': returns.std() * np.sqrt(252),
                'Skewness': returns.skew(),
                'Excess Kurtosis': returns.kurtosis()
            }).round(4)
            st.dataframe(stats_df, use_container_width=True, hide_index=True)

            # Download button
            st.subheader("💾 Download Results")
            results_dict = {
                'historical_var_10d': hist_var,
                'historical_es_10d': hist_es,
                'parametric_var_10d': param_var,
                'parametric_es_10d': param_es,
                'kupiec_failures': hist_backtest['failures'],
                'kupiec_p_value': hist_backtest['p_value'],
                'portfolio_volatility': port_ann_vol,
                'diversification_benefit': div_benefit
            }
            results_df = pd.DataFrame([results_dict])
            csv = results_df.to_csv(index=False).encode('utf-8')
            st.download_button("Download Results CSV", csv, "risk_results.csv", "text/csv")

        except Exception as e:
            st.error(f"An error occurred: {str(e)}")
            st.info("Try: fewer tickers, different date range, or check internet connection")

else:
    # Welcome screen
    st.info("👈 Configure parameters in the sidebar and click 'Run Analysis'")

    st.markdown("""
    ### Features

    - **Multiple VaR Methods**: Historical, Parametric (Delta-Normal), and Rolling Window
    - **Regulatory Backtesting**: Kupiec POF test, Basel Traffic Light framework
    - **Risk Metrics**: Volatility, diversification benefit, CAPM betas
    - **Interactive Visualizations**: Rolling risk metrics and exception timelines

    ### Example Usage

    1. Enter tickers (e.g., `AAPL, MSFT, GOOGL`)
    2. Set date range and confidence levels
    3. Click Run Analysis
    4. Interpret results with Basel traffic light zones
    """)

    # Show default example
    with st.expander("📖 Methodology Summary"):
        st.markdown("""
        - **Historical VaR**: Uses empirical return distribution (non-parametric)
        - **Parametric VaR**: Assumes normal distribution (fails under fat tails)
        - **Expected Shortfall (ES)**: Average loss beyond VaR (coherent risk measure)
        - **Kupiec Test**: Checks if failure rate matches confidence level
        - **Basel Traffic Light**: Regulatory acceptance zones (Green/Yellow/Red)
        - **Rolling Window**: Time-varying risk estimates (250-day standard)
        """)

