# -*- coding: utf-8 -*-
"""Risk_Metrics_Refactored_TrainRets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wC764P8VfWACyaZLDWtTjuk2oFo33BJ

# Portfolio Risk Metrics: VaR, ES & Backtesting Validation

> **Note:** This notebook documents the process of building, validating, and stress-testing market risk models from first principles. It prioritises transparency of reasoning over code minimalism.

This notebook computes descriptive statistics, constructs a multi-asset portfolio, implements three VaR/ES methodologies, and validates them against regulatory backtesting frameworks.

We use SPY instead of ^GSPC because SPY is actually tradeable.
"""

# ── Configuration ─────────────────────────────────────────────────────────────
# All parameters in one place — change here, flows through the entire notebook

TICKERS      = ['AAPL', 'SAIL.NS', 'MSFT', 'RELIANCE.NS', 'SPY']
START_DATE   = '2016-01-01'
END_DATE     = '2026-01-01'
SPLIT_DATE   = '2022-01-01'   # Train/test cutoff
MARKET       = 'SPY'          # Benchmark for beta/CAPM

ALPHA_VAR    = 0.99           # VaR confidence level
ALPHA_ES     = 0.975          # ES confidence level
RISK_FREE    = 0.02           # Annual risk-free rate (assumed, simplified)
TRADING_DAYS = 252            # Annual scaling factor
HOLDING_DAYS = 10             # Regulatory holding period (Basel)
N_SIM        = 10_000         # Monte Carlo simulation count
ROLL_WINDOW  = 250            # Rolling window (Basel standard: 250 days)

import pandas as pd
import numpy as np
from scipy.stats import norm, chi2
import matplotlib.pyplot as plt
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')

"""## 1. Data"""

data      = yf.download(TICKERS, start=START_DATE, end=END_DATE, auto_adjust=False)
adj_close = data['Adj Close'].dropna()

# Simple returns: intuitive, used for reporting and portfolio arithmetic
# Log returns: additive over time, preferred for statistical modelling
returns     = adj_close.pct_change().dropna()
log_returns = np.log(adj_close).diff().dropna()

print(f"Data loaded: {len(adj_close)} trading days | {adj_close.columns.tolist()}")
print(f"Date range:  {adj_close.index[0].date()} → {adj_close.index[-1].date()}")

"""## 2. Descriptive Statistics

We analyse returns rather than prices as price series are non-stationary and yield nonsensical regression results. Returns are stationary and comparable across assets.
"""

# Annualised moments
ann_mean = returns.mean() * TRADING_DAYS
ann_vol  = returns.std()  * np.sqrt(TRADING_DAYS)

print("=== Annualised Mean Return ===")
print(ann_mean.round(4))

print("\n=== Annualised Volatility ===")
print(ann_vol.round(4))

print("\n=== Skewness ===")
print(returns.skew().round(4))

print("\n=== Excess Kurtosis ===")
print(returns.kurtosis().round(4))

"""## 3. Correlation & Covariance

The covariance matrix drives portfolio risk. We construct it as Σ = Corr ⊙ (σᵢ · σⱼ) i.e., the Hadamard product of the correlation matrix and the outer product of annualised volatilities.
"""

corr_matrix     = returns.corr()
ann_vols        = returns.std() * np.sqrt(TRADING_DAYS)
cov_matrix_ann  = corr_matrix * np.outer(ann_vols, ann_vols)

print("Correlation Matrix:")
print(corr_matrix.round(3))

print("\nAnnualised Covariance Matrix:")
print(pd.DataFrame(cov_matrix_ann,
                   index=ann_vols.index,
                   columns=ann_vols.index).round(6))

# Sanity check: diagonal elements must equal variance (vol²)
print("\nDiagonal check (cov_ii should equal vol_i²):")
for t in returns.columns:
    print(f"  {t}: cov={cov_matrix_ann.loc[t,t]:.6f}  vol²={ann_vols[t]**2:.6f}  ✅")

"""## 4. Beta & CAPM Expected Return

Beta measures an asset's sensitivity to market movements. CAPM expected return: E(Rᵢ) = Rf + βᵢ · (E(Rm) − Rf)
"""

market_ret  = returns[MARKET]
stock_rets  = returns.drop(columns=[MARKET])

betas = {}
print(f"{'Asset':<15} {'Beta':>8} {'CAPM E(R)':>12}")
print("-" * 37)
for ticker in stock_rets.columns:
    cov_im = np.cov(stock_rets[ticker], market_ret)[0, 1]
    beta   = cov_im / np.var(market_ret)
    e_ret  = RISK_FREE + beta * (market_ret.mean() * TRADING_DAYS - RISK_FREE)
    betas[ticker] = beta
    print(f"{ticker:<15} {beta:>8.3f} {e_ret:>11.2%}")

"""## 5. Portfolio Construction

Equal-weighted portfolio. Portfolio variance: σ²_p = **w**ᵀ **Σ** **w**
"""

weights           = np.array([1 / len(TICKERS)] * len(TICKERS))
portfolio_var     = weights.T @ cov_matrix_ann @ weights
portfolio_vol_ann = np.sqrt(portfolio_var)
portfolio_returns = returns @ weights

avg_individual_vol = ann_vols.mean()
vol_reduction      = (avg_individual_vol - portfolio_vol_ann) / avg_individual_vol

print(f"Equal-weight portfolio annualised volatility: {portfolio_vol_ann:.4f} ({portfolio_vol_ann:.2%})")
print(f"Average individual asset volatility:          {avg_individual_vol:.4f} ({avg_individual_vol:.2%})")
print(f"Diversification benefit:                      {vol_reduction:.2%} reduction")

"""## 6. Train / Test Split

VaR thresholds are estimated on training data (2016–2021) and validated on unseen test data (2022–2026). This prevents look-ahead bias in backtesting.
"""

train_returns = portfolio_returns[portfolio_returns.index <  SPLIT_DATE]
test_returns  = portfolio_returns[portfolio_returns.index >= SPLIT_DATE]

print(f"Train: {train_returns.index[0].date()} → {train_returns.index[-1].date()} ({len(train_returns)} days)")
print(f"Test:  {test_returns.index[0].date()}  → {test_returns.index[-1].date()} ({len(test_returns)} days)")

"""## 7. Risk Metrics: VaR & Expected Shortfall

Regulatory frameworks (Basel III/IV) require 10-day risk measures. We compute 1-day VaR/ES and scale to 10 days using the square-root-of-time rule: σ_T = σ₁ · √T.

**Note on ES scaling:** Parametric ES does not scale exactly by √T unless μ = 0, because:

ES_T = T·μ + √T·σ · φ(z_α)/(1−α)

The φ(z)/(1−α) term amplifies the effect at high confidence levels, causing parametric ES to grow slightly faster than √T.
"""

# ── Historical VaR & ES ────────────────────────────────────────────────────────
var_1d_hist    = np.percentile(portfolio_returns, (1 - ALPHA_VAR) * 100)
var_10d_hist   = -var_1d_hist * np.sqrt(HOLDING_DAYS)

es_threshold   = np.percentile(portfolio_returns, (1 - ALPHA_ES) * 100)
tail_returns   = portfolio_returns[portfolio_returns <= es_threshold]
es_10d_hist    = -tail_returns.mean() * np.sqrt(HOLDING_DAYS)

# ── Parametric (Delta-Normal) VaR & ES ────────────────────────────────────────
mu    = portfolio_returns.mean()
sigma = portfolio_returns.std()

z_var              = norm.ppf(1 - ALPHA_VAR)
z_es               = norm.ppf(1 - ALPHA_ES)
var_10d_param      = -(mu + sigma * z_var) * np.sqrt(HOLDING_DAYS)
es_10d_param       = (mu + sigma * norm.pdf(z_es) / (1 - ALPHA_ES)) * np.sqrt(HOLDING_DAYS)

# Assertions — verify sign and ordering conventions
assert var_10d_hist  > 0, "Historical VaR must be positive (expressed as a loss)"
assert es_10d_hist   > 0, "Historical ES must be positive"
assert es_10d_hist  >= var_10d_hist,  "ES must be >= VaR (coherence)"
assert var_10d_param > 0, "Parametric VaR must be positive"
assert es_10d_param  > 0, "Parametric ES must be positive"
assert es_10d_param >= var_10d_param, "Parametric ES must be >= Parametric VaR"

print(f"{'Metric':<35} {'Historical':>12} {'Parametric':>12}")
print("-" * 60)
print(f"{'10-day 99% VaR':<35} {var_10d_hist:>11.2%} {var_10d_param:>11.2%}")
print(f"{'10-day 97.5% ES':<35} {es_10d_hist:>11.2%} {es_10d_param:>11.2%}")

"""## 8. Backtesting

Backtesting checks whether a VaR model's failure rate matches its stated confidence level. We implement three complementary frameworks, each adding a layer of diagnostic power.
"""

def kupiec_pof_test(returns, var_threshold, alpha=0.01):
    """
    Kupiec's Proportion of Failures (POF) test.

    Tests whether the observed VaR exception rate matches the
    expected rate (alpha) using a likelihood ratio test.

    H₀: failure rate = alpha (model is correctly calibrated)

    Parameters
    ----------
    returns       : array-like  Portfolio daily returns
    var_threshold : float       Positive VaR threshold (e.g. 0.017 for 1.7% loss)
    alpha         : float       Expected failure rate (default 0.01 for 99% VaR)

    Returns
    -------
    dict : LR statistic, p-value, reject_H0, failures, expected_failures
    """
    n            = len(returns)
    failures     = int(np.sum(returns < -var_threshold))
    failure_rate = failures / n
    expected     = n * alpha

    if failures == 0:
        LR = -2 * np.log((1 - alpha) ** n)
    elif failures == n:
        LR = -2 * np.log(alpha ** n)
    else:
        LR = -2 * np.log(
            ((1 - alpha) ** (n - failures) * alpha ** failures) /
            ((1 - failure_rate) ** (n - failures) * failure_rate ** failures)
        )

    critical_value = chi2.ppf(0.99, df=1)
    p_value        = 1 - chi2.cdf(LR, df=1)

    return {
        'failures'         : failures,
        'expected_failures': round(expected, 1),
        'failure_rate'     : f"{failure_rate:.2%}",
        'LR_statistic'     : round(LR, 4),
        'p_value'          : round(p_value, 4),
        'reject_H0'        : LR > critical_value,
    }


def christoffersen_test(returns, var_threshold, alpha=0.01):
    """
    Christoffersen's Conditional Coverage test.

    Extends Kupiec by also testing for independence of exceptions.
    Clusters of failures (e.g. all in one crisis month) indicate
    the model fails to capture volatility dynamics.

    H₀: failures are independent AND occur at rate alpha

    Returns
    -------
    dict : LR_uc (unconditional), LR_ind (independence), LR_cc (joint),
           p_value, reject_H0, pi0 (P(failure | no prior failure)),
           pi1 (P(failure | prior failure))
    """
    n        = len(returns)
    exc      = (returns < -var_threshold).astype(int)
    T00 = T01 = T10 = T11 = 0

    for i in range(1, n):
        prev, curr = exc.iloc[i-1], exc.iloc[i]
        if   prev == 0 and curr == 0: T00 += 1
        elif prev == 0 and curr == 1: T01 += 1
        elif prev == 1 and curr == 0: T10 += 1
        elif prev == 1 and curr == 1: T11 += 1

    x     = exc.sum()
    pi0   = T01 / (T00 + T01) if (T00 + T01) > 0 else 0
    pi1   = T11 / (T10 + T11) if (T10 + T11) > 0 else 0
    pi    = (T01 + T11) / (T00 + T01 + T10 + T11)

    LR_uc = -2 * np.log(
        ((1 - alpha) ** (n - x) * alpha ** x) /
        ((1 - x/n) ** (n - x) * (x/n) ** x)
    )

    if pi0 == 0 or pi1 == 0 or pi == 0:
        LR_ind = 0
    else:
        LR_ind = -2 * np.log(
            ((1 - pi) ** (T00 + T10) * pi ** (T01 + T11)) /
            ((1 - pi0) ** T00 * pi0 ** T01 * (1 - pi1) ** T10 * pi1 ** T11)
        )

    LR_cc   = LR_uc + LR_ind
    p_value = 1 - chi2.cdf(LR_cc, df=2)

    return {
        'failures'  : int(x),
        'LR_uc'     : round(LR_uc, 4),
        'LR_ind'    : round(LR_ind, 4),
        'LR_cc'     : round(LR_cc, 4),
        'p_value'   : round(p_value, 4),
        'reject_H0' : p_value < 0.01,
        'pi0'       : round(pi0, 4),
        'pi1'       : round(pi1, 4),
    }


def traffic_light_test(returns, var_threshold, alpha=0.01, window=250):
    """
    Basel Traffic Light test.

    Classifies VaR models into Green / Yellow / Red zones based on
    exception counts, scaled from the standard 250-day regulatory window.

    Basel zones (250-day, 99% VaR): Green 0–4, Yellow 5–9, Red 10+

    Returns
    -------
    dict : zone, failures, expected, green_threshold, yellow_threshold
    """
    n            = len(returns)
    failures     = int(np.sum(returns < -var_threshold))
    scale        = n / window
    green_max    = int(4 * scale)
    yellow_max   = int(9 * scale)

    if   failures <= green_max:  zone = "🟢 GREEN"
    elif failures <= yellow_max: zone = "🟡 YELLOW"
    else:                        zone = "🔴 RED"

    return {
        'failures'        : failures,
        'expected'        : round(n * alpha, 1),
        'failure_rate'    : f"{failures/n:.2%}",
        'zone'            : zone,
        'green_threshold' : green_max,
        'yellow_threshold': yellow_max,
    }

"""### 8.1 In-Sample Backtesting (2016–2021)

Thresholds estimated and tested on the same training data. This establishes a baseline. A well-calibrated model should pass here by construction.
"""

# VaR thresholds from full training data
hist_var  = -np.percentile(train_returns, (1 - ALPHA_VAR) * 100)
param_var = -(mu + sigma * norm.ppf(1 - ALPHA_VAR))  # 1-day parametric threshold

print("── Kupiec POF Test (In-Sample) ──")
h_kup = kupiec_pof_test(train_returns, hist_var,  alpha=1 - ALPHA_VAR)
p_kup = kupiec_pof_test(train_returns, param_var, alpha=1 - ALPHA_VAR)

results_is = pd.DataFrame([
    {'Model': 'Historical', **h_kup},
    {'Model': 'Parametric', **p_kup},
])
print(results_is[['Model','failures','expected_failures','failure_rate','p_value','reject_H0']].to_string(index=False))

print("\n── Christoffersen Test (In-Sample) ──")
h_cc = christoffersen_test(train_returns, hist_var,  alpha=1 - ALPHA_VAR)
p_cc = christoffersen_test(train_returns, param_var, alpha=1 - ALPHA_VAR)
print(f"Historical  — LR_cc={h_cc['LR_cc']}, p={h_cc['p_value']}, reject={h_cc['reject_H0']}, π₀={h_cc['pi0']}, π₁={h_cc['pi1']}")
print(f"Parametric  — LR_cc={p_cc['LR_cc']}, p={p_cc['p_value']}, reject={p_cc['reject_H0']}, π₀={p_cc['pi0']}, π₁={p_cc['pi1']}")

print("\n── Basel Traffic Light (In-Sample) ──")
h_tl = traffic_light_test(train_returns, hist_var,  alpha=1 - ALPHA_VAR)
p_tl = traffic_light_test(train_returns, param_var, alpha=1 - ALPHA_VAR)
print(f"Historical  — {h_tl['zone']} ({h_tl['failures']} failures, expected {h_tl['expected']})")
print(f"Parametric  — {p_tl['zone']} ({p_tl['failures']} failures, expected {p_tl['expected']})")

exc = (train_returns < -hist_var).astype(int)
print(f"Total failures: {exc.sum()}")
print(f"Consecutive failures: {((exc.shift(1) == 1) & (exc == 1)).sum()}")
print(f"First few exc values: {exc.values[:20]}")

"""Note: clustering is absent in the training period (2016–2021), reflecting relatively stable market conditions. The procyclicality of the parametric model becomes apparent in the out-of-sample period (2022–2026), where sustained volatility produces consecutive failures, suggesting the model's weakness is regime-dependent rather than constant.

### Backtesting VaR Models — Kupiec POF Test

To assess whether our VaR models are correctly calibrated, we apply Kupiec's Proportion of Failures (POF) test. The test evaluates whether the observed failure rate (returns exceeding the VaR threshold) matches the expected failure rate of 1% (for 99% VaR).

**Results:**

| Model | Failures | Expected | Failure Rate | p-value | Reject H₀? |
|-------|----------|----------|--------------|---------|------------|
| Historical VaR | 15 | 14.4 | 1.04% | 0.8683 | ❌ No |
| Parametric VaR | 26 | 14.4 | 1.81% | 0.0056 | ✅ Yes |

**Interpretation:**

The historical VaR model passes the Kupiec test (p = 0.8683), indicating it is well-calibrated to the empirical distribution of returns.

The parametric VaR model fails the test (p = 0.0056). With 26 exceptions versus 14.4 expected, the model systematically **underestimates risk**. This is consistent with the presence of fat tails and negative skew in the return distribution: the normal assumption underlying parametric VaR does not hold, leading to liberal (overly low) risk estimates.

This highlights the importance of model validation and the dangers of relying on parametric assumptions without diagnostic testing.

---

### Backtesting VaR Models — Christoffersen Conditional Coverage Test

While Kupiec's test evaluates whether the failure rate matches expectations, it ignores *when* failures occur. A model could have the correct failure rate but still be invalid if failures cluster. Christoffersen's test addresses this by jointly examining both the failure rate and the independence of failures.

The test combines two components:
1. **Unconditional coverage (Kupiec):** Are there too many or too few failures?
2. **Independence test:** Are failures randomly distributed or do they cluster?

**Results:**

| Model | Failures | Failure Rate | LR_uc | LR_ind | LR_cc | p-value | Reject H₀? |
|-------|----------|--------------|-------|--------|-------|---------|------------|
| Historical VaR | 15 | 1.04% | 0.0275 | 0.0 | 0.0275 | 0.9863| ❌ No |
| Parametric VaR | 26 | 1.81% | 7.6689 | 0.0 | 7.6689 | 0.0216 | ✅ Yes |

**Transition Probabilities:**

| Model | π₀ (failure after non-failure) | π₁ (failure after failure) |
|-------|--------------------------------|----------------------------|
| Historical VaR | 1.06% | 0.00% |
| Parametric VaR | 1.84% | 0.00% |

With π₁ = 0.00% for both models, no consecutive failure days occur in the training period — the independence assumption holds. The parametric model's rejection is driven entirely by the unconditional coverage component (too many failures), not clustering.

---

### Backtesting VaR Models — Basel Traffic Light Test

| Model | Failures | Zone | Interpretation |
|-------|----------|------|----------------|
| Historical VaR | 15 | 🟢 GREEN | Model is well-calibrated |
| Parametric VaR | 26 | 🟡 YELLOW | Model is questionable, investigate further |

---

### Summary — All In-Sample Backtests

| Model | Kupiec (p-value) | Christoffersen (p-value) | Traffic Light | Verdict |
|-------|-----------------|--------------------------|---------------|---------|
| Historical VaR | 0.8683 ✅ | 0.9863 ✅ | 🟢 GREEN | ✅ Valid |
| Parametric VaR | 0.0056 ❌ | 0.0216 ❌ | 🟡 YELLOW | ❌ Invalid |

### 8.2 Sanity Check — Synthetic Normal Data

If our parametric VaR is correctly implemented, it should pass Kupiec on data that is *actually* normally distributed. This confirms the implementation is correct and the real-data failure is due to fat tails, not a coding error.
"""

np.random.seed(50)
synthetic = np.random.normal(loc=mu, scale=sigma, size=len(train_returns))
synth_var = -(mu + sigma * norm.ppf(1 - ALPHA_VAR))

synth_result = kupiec_pof_test(synthetic, synth_var, alpha=1 - ALPHA_VAR)
print("Synthetic Normal Data — Kupiec Test:")
print(f"  Failures:     {synth_result['failures']} / {len(synthetic)}")
print(f"  Expected:     {synth_result['expected_failures']}")
print(f"  p-value:      {synth_result['p_value']}")
print(f"  Reject H₀:   {synth_result['reject_H0']}")
print(f"  → Parametric VaR passes on normal data ✅ — real-data failure is distributional, not a bug.")

"""### 8.3 Out-of-Sample Backtesting (2022–2026)

Thresholds are fixed from training data. Testing on unseen data reveals whether models generalise, which is a good test of robustness.
"""

print("── Out-of-Sample Kupiec Test ──")
h_kup_oos = kupiec_pof_test(test_returns, hist_var,  alpha=1 - ALPHA_VAR)
p_kup_oos = kupiec_pof_test(test_returns, param_var, alpha=1 - ALPHA_VAR)

oos_df = pd.DataFrame([
    {'Model': 'Historical', **h_kup_oos},
    {'Model': 'Parametric', **p_kup_oos},
])
print(oos_df[['Model','failures','expected_failures','failure_rate','p_value','reject_H0']].to_string(index=False))

print("\n── Out-of-Sample Christoffersen Test ──")
h_cc_oos = christoffersen_test(test_returns, hist_var,  alpha=1 - ALPHA_VAR)
p_cc_oos = christoffersen_test(test_returns, param_var, alpha=1 - ALPHA_VAR)
print(f"Historical  — p={h_cc_oos['p_value']}, reject={h_cc_oos['reject_H0']}")
print(f"Parametric  — p={p_cc_oos['p_value']}, reject={p_cc_oos['reject_H0']}")

print("\n── Out-of-Sample Traffic Light ──")
h_tl_oos = traffic_light_test(test_returns, hist_var,  alpha=1 - ALPHA_VAR)
p_tl_oos = traffic_light_test(test_returns, param_var, alpha=1 - ALPHA_VAR)
print(f"Historical  — {h_tl_oos['zone']} ({h_tl_oos['failures']} failures)")
print(f"Parametric  — {p_tl_oos['zone']} ({p_tl_oos['failures']} failures)")

print("\n── In-Sample vs Out-of-Sample Comparison ──")
comparison = pd.DataFrame({
    'Model'               : ['Historical', 'Parametric'],
    'IS failures'         : [h_kup['failures'],     p_kup['failures']],
    'OOS failures'        : [h_kup_oos['failures'],  p_kup_oos['failures']],
    'IS p-value'          : [h_kup['p_value'],       p_kup['p_value']],
    'OOS p-value'         : [h_kup_oos['p_value'],   p_kup_oos['p_value']],
    'IS verdict'          : ['✅ Pass' if not h_kup['reject_H0']     else '❌ Fail',
                             '✅ Pass' if not p_kup['reject_H0']     else '❌ Fail'],
    'OOS verdict'         : ['✅ Pass' if not h_kup_oos['reject_H0'] else '❌ Fail',
                             '✅ Pass' if not p_kup_oos['reject_H0'] else '❌ Fail'],
})
print(comparison.to_string(index=False))

"""### Summary — In-Sample vs Out-of-Sample

| Model | In-sample failures | Out-of-sample failures | In-sample p-value | Out-of-sample p-value | In-sample Verdict | Out-of-sample verdict |
|-------|-------------------|----------------------|-------------------|----------------------|-------------------|----------------------|
| Historical VaR | 15 | 3 | 0.8683 | 0.0129 | Pass ✅ | Pass ✅ |
| Parametric VaR | 26 | 13 | 0.0056 | 0.2860 | Fail ❌ | Pass ✅ |

## 9. Historical Monte Carlo VaR

Historical Monte Carlo resamples (with replacement) from the empirical training distribution to generate simulated return paths. This preserves real-world fat tails and cross-asset correlations, including crash-period behaviour, rather than imposing a Gaussian assumption.

**Note:** Because this method draws from the same empirical distribution as Historical Simulation, similar VaR thresholds are expected. The two methods are not independent but share the same source data.
"""

np.random.seed(42)
sim_returns    = np.random.choice(train_returns.values, size=N_SIM, replace=True)
mc_var         = -np.percentile(sim_returns, (1 - ALPHA_VAR) * 100)

mc_kup = kupiec_pof_test(test_returns, mc_var, alpha=1 - ALPHA_VAR)
mc_cc  = christoffersen_test(test_returns, mc_var, alpha=1 - ALPHA_VAR)
mc_tl  = traffic_light_test(test_returns, mc_var, alpha=1 - ALPHA_VAR)

print(f"MC VaR threshold:  {mc_var:.4f}")
print(f"Historical threshold: {hist_var:.4f}  (expected to be similar)")
print(f"\nKupiec: failures={mc_kup['failures']}, p={mc_kup['p_value']}, reject={mc_kup['reject_H0']}")
print(f"Christoffersen: p={mc_cc['p_value']}, reject={mc_cc['reject_H0']}")
print(f"Traffic Light: {mc_tl['zone']}")

print("── Final Model Comparison ──")
final = pd.DataFrame({
    'Model'        : ['Historical VaR', 'Parametric VaR', 'Historical MC VaR'],
    'IS failures'  : [h_kup['failures'],     p_kup['failures'],     'N/A'],
    'OOS failures' : [h_kup_oos['failures'],  p_kup_oos['failures'],  mc_kup['failures']],
    'IS p-value'   : [h_kup['p_value'],       p_kup['p_value'],       'N/A'],
    'OOS p-value'  : [h_kup_oos['p_value'],   p_kup_oos['p_value'],   mc_kup['p_value']],
    'IS verdict'   : ['✅ Pass', '❌ Fail', 'N/A'],
    'OOS verdict'  : [
        '✅ Pass' if not h_kup_oos['reject_H0'] else '❌ Fail',
        '✅ Pass' if not p_kup_oos['reject_H0'] else '❌ Fail',
        '✅ Pass' if not mc_kup['reject_H0']    else '❌ Fail',
    ],
})
print(final.to_string(index=False))

"""##10. Rolling Window Analysis"""

# ── Rolling Window Analysis ──────────────────────────────────────────────────────
# Fixed thresholds ignore that risk changes over time. Rolling windows reveal
# how risk evolves: spiking during crises, contracting during calm periods.

rolling_var = []
rolling_es = []
rolling_dates = portfolio_returns.index[ROLL_WINDOW:]

for i in range(ROLL_WINDOW, len(portfolio_returns)):
    window = portfolio_returns.iloc[i - ROLL_WINDOW:i]
    rolling_var.append(np.percentile(window, 1))
    # ES at 97.5% (tail average beyond 97.5th percentile)
    tail = window[window <= np.percentile(window, 2.5)]
    rolling_es.append(tail.mean() if len(tail) > 0 else np.nan)

# Convert to arrays and scale to 10-day
rolling_var_10d = -np.array(rolling_var) * np.sqrt(HOLDING_DAYS)
rolling_es_10d  = -np.array(rolling_es) * np.sqrt(HOLDING_DAYS)

print(f"Rolling window analysis complete: {len(rolling_dates)} windows")
print(f"  VaR range:  {rolling_var_10d.min():.2%} – {rolling_var_10d.max():.2%}")
print(f"  ES range:   {rolling_es_10d.min():.2%} – {rolling_es_10d.max():.2%}")

"""#11. Rolling Backtesting"""

# ── Rolling Backtesting (Dynamic Thresholds) ──────────────────────────────────
# Unlike fixed-threshold backtesting, rolling backtesting recomputes VaR
# each day using only past data (no look-ahead). This mirrors how risk
# systems actually operate and provides a stricter test of model performance.

print("\n" + "="*60)
print("Rolling Backtesting (Dynamic 99% VaR)")
print("="*60)

ROLL_WINDOW = 250  # Basel standard

# Storage for rolling results
roll_exceptions = []
roll_var_series = []
roll_dates = []

for i in range(ROLL_WINDOW, len(portfolio_returns)):
    # Use only data up to yesterday to predict today's VaR
    window = portfolio_returns.iloc[i - ROLL_WINDOW:i]

    # Historical VaR at 99% (1st percentile)
    var_t = np.percentile(window, 1)
    roll_var_series.append(var_t)

    # Check if today's return exceeds the threshold
    actual_return = portfolio_returns.iloc[i]
    is_exception = actual_return < var_t
    roll_exceptions.append(is_exception)
    roll_dates.append(portfolio_returns.index[i])

roll_exceptions = np.array(roll_exceptions)
n_roll = len(roll_exceptions)
failures_roll = roll_exceptions.sum()
failure_rate_roll = failures_roll / n_roll
expected_roll = n_roll * 0.01

print(f"\nRolling window length: {ROLL_WINDOW} days")
print(f"Test period:           {roll_dates[0].date()} → {roll_dates[-1].date()}")
print(f"Number of tests:       {n_roll}")
print(f"\nFailures:              {failures_roll} / {n_roll} ({failure_rate_roll:.2%})")
print(f"Expected failures:     {expected_roll:.1f}")
print(f"Difference:            {failures_roll - expected_roll:+.1f}")

# Run Kupiec test on rolling exceptions
def kupiec_from_exceptions(exceptions, alpha=0.01):
    """Kupiec test from pre-computed exception series"""
    n = len(exceptions)
    x = exceptions.sum()
    failure_rate = x / n
    expected = n * alpha

    if x == 0:
        LR = -2 * np.log((1 - alpha) ** n)
    elif x == n:
        LR = -2 * np.log(alpha ** n)
    else:
        LR = -2 * np.log(
            ((1 - alpha) ** (n - x) * alpha ** x) /
            ((1 - failure_rate) ** (n - x) * failure_rate ** x)
        )

    p_value = 1 - chi2.cdf(LR, df=1)
    reject = p_value < 0.01

    return {
        'failures': x,
        'expected': round(expected, 1),
        'failure_rate': f"{failure_rate:.2%}",
        'p_value': round(p_value, 4),
        'reject': reject
    }

roll_kupiec = kupiec_from_exceptions(roll_exceptions)

print(f"\nKupiec Test Results:")
print(f"  p-value:      {roll_kupiec['p_value']}")
print(f"  Reject H₀:    {'✅ No' if not roll_kupiec['reject'] else '❌ Yes'}")

# Compare with fixed-threshold backtesting
print("\n" + "-"*40)
print("Comparison: Fixed vs Rolling Thresholds")
print("-"*40)

# Fixed thresholds from training period (already computed earlier)
train_exceptions = portfolio_returns < -hist_var
fixed_failures = train_exceptions.sum()
fixed_rate = fixed_failures / len(portfolio_returns)

print(f"\nFixed threshold (full-sample VaR):")
print(f"  Failures:  {fixed_failures} / {len(portfolio_returns)} ({fixed_rate:.2%})")
print(f"  Expected:  {len(portfolio_returns) * 0.01:.1f}")

print(f"\nRolling threshold (dynamic VaR):")
print(f"  Failures:  {failures_roll} / {n_roll} ({failure_rate_roll:.2%})")
print(f"  Expected:  {expected_roll:.1f}")

# Interpretation
print("\n" + "-"*40)
print("Interpretation")
print("-"*40)

if failures_roll <= expected_roll * 1.2:  # within 20% of expected
    print("✅ Rolling historical VaR passes the backtest.")
    print("   The dynamic threshold adapts well to changing volatility.")
else:
    print("⚠️ Rolling historical VaR shows elevated exceptions.")
    print("   Consider shorter windows or alternative volatility models.")

print(f"\n💡 Key insight: Fixed-threshold backtesting (OOS) gave {p_kup_oos['failures']} failures,")
print(f"   while rolling backtesting gives {failures_roll} failures over a similar period.")
print(f"   Rolling is stricter because thresholds tighten during volatile periods.")

print(f"hist_var: {hist_var}")
print(f"Threshold for failure: {-hist_var}")

# Check your actual threshold values
print(f"hist_var from earlier: {hist_var}")
print(f"1st percentile of returns: {np.percentile(portfolio_returns, 1)}")
print(f"Portfolio returns < -0.035: {(portfolio_returns < -0.035).sum()} / {len(portfolio_returns)}")
print(f"Portfolio returns < 0.035: {(portfolio_returns < 0.035).sum()} / {len(portfolio_returns)}")

# ── Rolling Parametric VaR Backtesting ──────────────────────────────────────────
print("\n" + "="*60)
print("Rolling Parametric VaR Backtesting (Dynamic 99% VaR)")
print("="*60)

roll_param_exceptions = []
roll_param_var_series = []
roll_dates_param = []

for i in range(ROLL_WINDOW, len(portfolio_returns)):
    window = portfolio_returns.iloc[i - ROLL_WINDOW:i]
    mu_w = window.mean()
    sigma_w = window.std()
    # Parametric VaR (positive threshold) - FIXED: removed the negative sign
    var_t = mu_w + sigma_w * norm.ppf(0.99)
    roll_param_var_series.append(var_t)
    roll_dates_param.append(portfolio_returns.index[i])

    actual_return = portfolio_returns.iloc[i]
    roll_param_exceptions.append(actual_return < -var_t)

    # Diagnostic for first two windows
    if i == ROLL_WINDOW or i == ROLL_WINDOW + 1:
        print(f"i={i}: mu={mu_w:.6f}, sigma={sigma_w:.6f}, var_t={var_t:.6f}, -var_t={-var_t:.6f}, actual={actual_return:.6f}, exc={actual_return < -var_t}")

roll_param_exceptions = np.array(roll_param_exceptions)
n_roll_param = len(roll_param_exceptions)
failures_param_roll = roll_param_exceptions.sum()
failure_rate_param_roll = failures_param_roll / n_roll_param if n_roll_param > 0 else 0
expected_roll = n_roll_param * 0.01

print(f"\nRolling window length: {ROLL_WINDOW} days")
print(f"Test period:           {roll_dates_param[0].date()} → {roll_dates_param[-1].date()}")
print(f"Number of tests:       {n_roll_param}")
print(f"\nFailures:              {failures_param_roll} / {n_roll_param} ({failure_rate_param_roll:.2%})")
print(f"Expected failures:     {expected_roll:.1f}")

roll_param_kupiec = kupiec_from_exceptions(roll_param_exceptions)
print(f"\nKupiec Test Results:")
print(f"  p-value:      {roll_param_kupiec['p_value']}")
print(f"  Reject H₀:    {'✅ No' if not roll_param_kupiec['reject'] else '❌ Yes'}")

# ── Rolling Monte Carlo VaR Backtesting ─────────────────────────────────────────
print("\n" + "="*60)
print("Rolling Monte Carlo VaR Backtesting (Dynamic 99% VaR)")
print("="*60)

np.random.seed(42)
roll_mc_exceptions = []
roll_dates_mc = []
N_SIM_ROLL = 5000  # Lower for speed

for i in range(ROLL_WINDOW, len(portfolio_returns)):
    window = portfolio_returns.iloc[i - ROLL_WINDOW:i]
    sim_returns = np.random.choice(window.values, size=N_SIM_ROLL, replace=True)
    var_t = -np.percentile(sim_returns, 1)
    roll_dates_mc.append(portfolio_returns.index[i])
    actual_return = portfolio_returns.iloc[i]
    roll_mc_exceptions.append(actual_return < -var_t)

roll_mc_exceptions = np.array(roll_mc_exceptions)
n_roll_mc = len(roll_mc_exceptions)
failures_mc_roll = roll_mc_exceptions.sum()
failure_rate_mc_roll = failures_mc_roll / n_roll_mc if n_roll_mc > 0 else 0

print(f"\nRolling window length: {ROLL_WINDOW} days")
print(f"Test period:           {roll_dates_mc[0].date()} → {roll_dates_mc[-1].date()}")
print(f"Number of tests:       {n_roll_mc}")
print(f"\nFailures:              {failures_mc_roll} / {n_roll_mc} ({failure_rate_mc_roll:.2%})")
print(f"Expected failures:     {n_roll_mc * 0.01:.1f}")

roll_mc_kupiec = kupiec_from_exceptions(roll_mc_exceptions)
print(f"\nKupiec Test Results:")
print(f"  p-value:      {roll_mc_kupiec['p_value']}")
print(f"  Reject H₀:    {'✅ No' if not roll_mc_kupiec['reject'] else '❌ Yes'}")

# ── Rolling Christoffersen Test ─────────────────────────────────────────────────
def christoffersen_from_exceptions(exceptions, alpha=0.01):
    """Christoffersen test from pre-computed exception series"""
    n = len(exceptions)
    if n == 0:
        return {'p_value': 1.0, 'reject_H0': False, 'LR_cc': 0}

    exc = exceptions.astype(int)
    T00 = T01 = T10 = T11 = 0

    for i in range(1, n):
        prev, curr = exc[i-1], exc[i]
        if prev == 0 and curr == 0:
            T00 += 1
        elif prev == 0 and curr == 1:
            T01 += 1
        elif prev == 1 and curr == 0:
            T10 += 1
        elif prev == 1 and curr == 1:
            T11 += 1

    x = exc.sum()
    pi0 = T01 / (T00 + T01) if (T00 + T01) > 0 else 0
    pi1 = T11 / (T10 + T11) if (T10 + T11) > 0 else 0
    pi = (T01 + T11) / (T00 + T01 + T10 + T11) if (T00 + T01 + T10 + T11) > 0 else 0

    LR_uc = -2 * np.log(
        ((1 - alpha) ** (n - x) * alpha ** x) /
        ((1 - x/n) ** (n - x) * (x/n) ** x)
    )

    if pi0 == 0 or pi1 == 0 or pi == 0:
        LR_ind = 0
    else:
        LR_ind = -2 * np.log(
            ((1 - pi) ** (T00 + T10) * pi ** (T01 + T11)) /
            ((1 - pi0) ** T00 * pi0 ** T01 * (1 - pi1) ** T10 * pi1 ** T11)
        )

    LR_cc = LR_uc + LR_ind
    p_value = 1 - chi2.cdf(LR_cc, df=2)

    return {
        'LR_cc': round(LR_cc, 4),
        'p_value': round(p_value, 4),
        'reject_H0': p_value < 0.01,
        'pi0': round(pi0, 4),
        'pi1': round(pi1, 4)
    }

# Run Christoffersen on rolling exceptions
roll_hist_cc = christoffersen_from_exceptions(roll_exceptions)
roll_param_cc = christoffersen_from_exceptions(roll_param_exceptions)
roll_mc_cc = christoffersen_from_exceptions(roll_mc_exceptions)

print("\n" + "="*60)
print("Rolling Backtesting — Christoffersen Test")
print("="*60)
print(f"Historical VaR:  LR_cc={roll_hist_cc['LR_cc']}, p={roll_hist_cc['p_value']}, reject={roll_hist_cc['reject_H0']}")
print(f"Parametric VaR:  LR_cc={roll_param_cc['LR_cc']}, p={roll_param_cc['p_value']}, reject={roll_param_cc['reject_H0']}")
print(f"Monte Carlo VaR:  LR_cc={roll_mc_cc['LR_cc']}, p={roll_mc_cc['p_value']}, reject={roll_mc_cc['reject_H0']}")

# ── Rolling Traffic Light Test ──────────────────────────────────────────────────
def traffic_light_from_exceptions(exceptions, alpha=0.01, window=250):
    """Traffic Light test from pre-computed exception series"""
    n = len(exceptions)
    failures = exceptions.sum()
    scale = n / window
    green_max = int(4 * scale)
    yellow_max = int(9 * scale)

    if failures <= green_max:
        zone = "🟢 GREEN"
    elif failures <= yellow_max:
        zone = "🟡 YELLOW"
    else:
        zone = "🔴 RED"

    return {'zone': zone, 'failures': failures, 'green_threshold': green_max, 'yellow_threshold': yellow_max}

roll_hist_tl = traffic_light_from_exceptions(roll_exceptions)
roll_param_tl = traffic_light_from_exceptions(roll_param_exceptions)
roll_mc_tl = traffic_light_from_exceptions(roll_mc_exceptions)

print("\n" + "="*60)
print("Rolling Backtesting — Traffic Light Test")
print("="*60)
print(f"Historical VaR:  {roll_hist_tl['zone']} ({roll_hist_tl['failures']} failures)")
print(f"Parametric VaR:  {roll_param_tl['zone']} ({roll_param_tl['failures']} failures)")
print(f"Monte Carlo VaR:  {roll_mc_tl['zone']} ({roll_mc_tl['failures']} failures)")

print("\n" + "-"*80)
print("Rolling Backtesting Complete Results (250-day windows)")
print("-"*80)

results_roll_full = pd.DataFrame({
    'Model': ['Historical VaR', 'Parametric VaR', 'Monte Carlo VaR'],
    'Failures': [failures_roll, failures_param_roll, failures_mc_roll],
    'Expected': [expected_roll, n_roll_param * 0.01, n_roll_mc * 0.01],
    'Kupiec p-value': [roll_kupiec['p_value'], roll_param_kupiec['p_value'], roll_mc_kupiec['p_value']],
    'Kupiec Reject': ['❌' if roll_kupiec['reject'] else '✅',
                      '❌' if roll_param_kupiec['reject'] else '✅',
                      '❌' if roll_mc_kupiec['reject'] else '✅'],
    'Christoffersen p-value': [roll_hist_cc['p_value'], roll_param_cc['p_value'], roll_mc_cc['p_value']],
    'Christoffersen Reject': ['❌' if roll_hist_cc['reject_H0'] else '✅',
                               '❌' if roll_param_cc['reject_H0'] else '✅',
                               '❌' if roll_mc_cc['reject_H0'] else '✅'],
    'Traffic Light': [roll_hist_tl['zone'], roll_param_tl['zone'], roll_mc_tl['zone']]
})
print(results_roll_full.to_string(index=False))

"""## 10. Visualisations"""

# ── Visualisations ──────────────────────────────────────────────────────────────

# Prepare rolling data (if not already computed)
if 'rolling_var_10d' not in dir():
    rolling_var = []
    rolling_es = []
    rolling_dates = portfolio_returns.index[ROLL_WINDOW:]

    for i in range(ROLL_WINDOW, len(portfolio_returns)):
        window = portfolio_returns.iloc[i - ROLL_WINDOW:i]
        rolling_var.append(np.percentile(window, 1))
        tail = window[window <= np.percentile(window, 2.5)]
        rolling_es.append(tail.mean() if len(tail) > 0 else np.nan)

    rolling_var_10d = -np.array(rolling_var) * np.sqrt(HOLDING_DAYS)
    rolling_es_10d = -np.array(rolling_es) * np.sqrt(HOLDING_DAYS)

fig, axes = plt.subplots(3, 1, figsize=(14, 14))

# 1. Rolling risk metrics over time
axes[0].plot(rolling_dates, rolling_var_10d, label='Rolling 99% 10-day VaR', linewidth=1.5)
axes[0].plot(rolling_dates, rolling_es_10d, label='Rolling 97.5% 10-day ES', linewidth=1.5, linestyle='--')
axes[0].axvline(pd.Timestamp(SPLIT_DATE), color='grey', linestyle='--', alpha=0.7, label='Train/Test split')
axes[0].set_title('Rolling Risk Metrics Over Time (250-day windows)', fontsize=12)
axes[0].legend()
axes[0].set_ylabel('Potential Loss')
axes[0].yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))

# 2. Portfolio returns with VaR/ES thresholds
axes[1].plot(portfolio_returns.index, portfolio_returns, alpha=0.5, label='Daily Returns')
axes[1].axhline(-hist_var, color='red', linestyle='--', label=f'99% VaR ({hist_var:.2%})')
axes[1].axhline(-es_10d_hist/np.sqrt(10), color='darkred', linestyle=':', label=f'97.5% ES (1-day equiv)')
axes[1].axvline(pd.Timestamp(SPLIT_DATE), color='grey', linestyle='--', alpha=0.7, label='Train/Test split')
axes[1].set_title('Portfolio Returns with VaR/ES Thresholds', fontsize=12)
axes[1].legend()
axes[1].set_ylabel('Daily Return')
axes[1].yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.1%}'))

# 3. Historical vs Parametric comparison
metrics = ['99% VaR (10-day)', '97.5% ES (10-day)']
hist_vals = [var_10d_hist, es_10d_hist]
param_vals = [var_10d_param, es_10d_param]
x = np.arange(len(metrics))
axes[2].bar(x - 0.2, hist_vals, 0.4, label='Historical')
axes[2].bar(x + 0.2, param_vals, 0.4, label='Parametric')
axes[2].set_xticks(x)
axes[2].set_xticklabels(metrics)
axes[2].set_ylabel('Loss')
axes[2].set_title('Historical vs Parametric Risk Estimates', fontsize=12)
axes[2].legend()
axes[2].yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.1%}'))

plt.tight_layout()
plt.show()

"""## 11. Results & Conclusions

We tested three VaR models — Historical, Parametric (Delta-Normal), and Historical Monte Carlo — on a 5-stock equal-weighted portfolio (2016–2026 data), using a strict train/test split: thresholds estimated on 2016–2021 data only, validated on unseen 2022–2026 data.

**In-sample results** (2016–2021):
- ✅ Historical VaR: 15 failures (p=0.8683): passed
- ❌ Parametric VaR: 26 failures (p=0.0056): failed
- Historical MC: not tested in-sample (draws from same distribution as Historical)

**Out-of-sample results** (2022–2026):
- ✅ Historical VaR: 3 failures (p=0.0129): passed (narrowly)
- ✅ Parametric VaR: 13 failures (p=0.2860): passed
- ✅ Historical MC VaR: 3 failures (p=0.0129): passed

*All p-values use a 1% significance level, consistent with Basel regulatory standards for 99% VaR backtesting.*

### Rolling Backtesting Summary (250-day windows)

| Model | Kupiec | Christoffersen | Traffic Light | Verdict |
|-------|--------|----------------|---------------|---------|
| Historical VaR | ❌ Fail | ❌ Fail | 🟡 YELLOW | Invalid |
| Parametric VaR | ✅ Pass | ❌ Fail | 🟢 GREEN | Questionable |
| Monte Carlo VaR | ✅ Pass | ❌ Fail | 🟢 GREEN | Questionable |

**Key finding:** All three models fail Christoffersen, indicating that none capture volatility clustering. The parametric model passes Kupiec but fails independence — it has the right number of failures but they cluster, revealing a timing problem. This suggests that while average risk estimates may be acceptable, the models systematically miss regime shifts, which is a serious limitation for real-time risk monitoring.

### The Counterintuitive Finding

All three models pass out-of-sample — including the parametric model that failed in-sample. This is not a contradiction. It reflects something important about **estimation window effects**.

| Model | In-sample | Out-of-sample | Why |
|-------|-----------|---------------|-----|
| **Historical VaR** | ✅ Pass | ✅ Pass (narrow) | Threshold calibrated on calm 2016–2021 data; conservative enough to hold in stress period |
| **Parametric VaR** | ❌ Fail | ✅ Pass | Underestimates risk in-sample due to fat tails, but the resulting lower threshold happens to generalise well OOS |
| **Historical MC VaR** | N/A | ✅ Pass | Inherits Historical VaR threshold; same behaviour |

The parametric model fails in-sample because it underestimates tail risk — it produces too many VaR exceptions relative to its stated confidence level (26 vs 14.4 expected). But that same underestimation produces a *lower* threshold, which when applied to the more volatile 2022–2026 period, catches enough exceptions to pass statistically.

This illustrates a subtle but important principle: **a model can be wrong for the right reasons, or right for the wrong reasons.** The parametric model passes OOS because its miscalibration happened to offset the regime shift, not because normality holds.

### The Deeper Issue: Estimation Window Risk

The most important variable in this analysis is not the model — it is the **estimation window**. Thresholds calibrated on calm data (2016–2021) are lower and more conservative when applied forward. Thresholds calibrated on the full dataset (including the volatile 2022–2026 period) are higher and appear too conservative OOS.

The rolling backtest confirms this sensitivity: when thresholds are recalibrated continuously (rolling window), the historical model fails (35 failures, p=0.0069), revealing that fixed-threshold success depends heavily on the chosen estimation period.

This sensitivity to the estimation window is itself a form of model risk, and it is one of the key motivations for:

- **Rolling window estimation:** recalibrating thresholds continuously rather than fixing them
- **GARCH models:** explicitly modelling time-varying volatility rather than assuming it is constant
- **Regime-switching models:** using different parameters for different market environments

### Next Steps

- **GARCH models:** time-varying volatility estimation
- **FHS (Filtered Historical Simulation):** GARCH + historical resampling
- **Stress testing:** extreme scenario analysis
- **Regime-switching models:** different rules for different market environments
"""